#!/bin/sh
set -e

# Create .env from environment variables if not already present
if [ ! -f /app/.env ]; then
  cat > /app/.env << EOF
APP_NAME=${APP_NAME:-"AI Summarizer"}
APP_ENV=${APP_ENV:-production}
APP_DEBUG=${APP_DEBUG:-false}
APP_URL=${APP_URL:-http://localhost:8000}
APP_KEY=${APP_KEY}

DB_CONNECTION=${DB_CONNECTION:-pgsql}
DB_HOST=${DB_HOST:-postgres}
DB_PORT=${DB_PORT:-5432}
DB_DATABASE=${DB_DATABASE:-summarizer}
DB_USERNAME=${DB_USERNAME:-summarizer}
DB_PASSWORD=${DB_PASSWORD}

QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
SQS_PREFIX=${SQS_PREFIX}
SQS_QUEUE=${SQS_QUEUE}

LLM_PROVIDER=${LLM_PROVIDER:-fake}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
ANTHROPIC_MODEL=${ANTHROPIC_MODEL}

MAX_INPUT_TOKENS=${MAX_INPUT_TOKENS:-12000}
RATE_LIMIT_PER_HOUR=${RATE_LIMIT_PER_HOUR:-20}
FETCH_TIMEOUT_SECONDS=${FETCH_TIMEOUT_SECONDS:-10}
FETCH_MAX_BYTES=${FETCH_MAX_BYTES:-2000000}

FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
EOF
fi

# Execute the passed command
exec "$@"
